### ISSUE TITLE
新更新的，变动好大，能简单介绍下思路吗？

### ISSUE THREAD

**Issue by Leadrive** [vgoio/vgo#117]
以前的很多模块都不在了，比如fdb_store.go
请问持久化，TIDB这些，后续是如何支持的？
谢谢。

**Comment by sunface** [comment]
东西大体没有变，一些代码组织结构和命名在调整中，很快就会上来，包括mysql(tidb)的持久化支持，目前已经支持fdb(foudationDB)了
