### ISSUE TITLE
  关于cluster模式能否提供一点说明

### ISSUE THREAD

**Issue by vearne** [vgoio/vgo#97]
meq看上去很有意思，我想深入的阅读下代码，可是文档资料有点少

**Comment by sunface** [comment]
你好，产品和技术文档正在制作中，可以持续关注一下官网 :)

**Comment by sunface** [comment]
我这里可以大概简单说明一下：
Cluster基于gossip协议，分为两个部分
- session(subscriptor)信息同步，一个新节点在启动的时候会选择一个老节点，然后拉取老节点的所有session信息；同时有用户订阅/取消时会广播给所有节点, 代码在subtrie.go和cluster.go中
- 内存存储模式下(存储分为两个模式，内存和foundationDB，前者更多用于非持久化和测试开发场景)的数据同步，每发布一条qos==1的消息，都会同步到所有节点，做数据的全存储，代码在mem_store.go和cluster.go中

**Comment by lchjczw** [comment]
期待文档的出现，我也在看cluster，我没有找到授权代码在哪里， @sunface 有授权吗？
